# Generated by Django 4.2.10 on 2024-10-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='name',
        ),
        migrations.AddField(
            model_name='app',
            name='caption',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='app',
            name='image',
            field=models.ImageField(default='file.png', upload_to='images'),
        ),
    ]
