# Generated by Django 4.2.10 on 2024-10-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_app_name_app_caption_app_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='file.png', upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='app',
        ),
    ]
